### PR TITLE
Code Refactors

### PR DESCRIPTION
**Pull request by etonotieno**
In this pull request, I have migrated the gradle dependencies to **deps.gradle** file and changed the adapters to ListAdapter. If possible can you change the firebase dependencies to the same version.  Please check the PR and send more feedback on it.

### CODE REVIEW

**Comment by wangerekaharun** [comment]
Hi @CodeZilla7  i have reviewed your PR and i have some issues i noted, first in the **deps.gradle** file you have declared the dependancies versions which is not recommended as gradle will not detect the updates for the libraries, secondly is that firebase dependancies as from **15.0.0** have **independent** versions meaning that you cannot declare same versions for all of them. Another thing i have realized is that I don't understand why you have to switch from recycleview adapter to listview adpater where as we are not using ListView for the project, the guidelines recommend we use recycleview adapter. Kindly refer to [https://github.com/droidconKE/droidconKE/blob/master/CONTRIBUTING.md](url) for the CONTRIBUTING GUIDELINES for this project. Also describe your changes and explanatory backup for the changes and also a demo for the same.

**Comment by etonotieno** [comment]
The adapter that is in the PR is not for a ListView, it's a RecyclerView.Adapter. It's a new type of adapter for RecyclerViews that was added in the version 27.1.0 support libraries, you can check the documentation for more details [Link to Docs](https://developer.android.com/reference/android/support/v7/recyclerview/extensions/ListAdapter). This type of adapter helps us to calculate diffs between lists asynchronously and update accordingly. As for the **deps.gradle** file, I will make the appropriate changes. Thanks for the feedback.

**Comment by etonotieno** [comment]
I would also like some clarification on the Contributing guidelines. For example, it says that I need to make a PR against the develop branch which makes it harder to merge commits since the branch is actively being updated. I am new to this so I don't have much experience making pull requests in the correct way.

**Comment by wangerekaharun** [comment]
@CodeZilla7 I will look into the docs and make the necessary changes, For now we have not yet released the app for collaboration. Wait until first version is released then you will be able to contribute to the project.

**Pull request closed without merging**
